server:
  port: 8080
  servlet:
    session:
      timeout: 7d
  #7天分钟，测试的话时间不能太短，否则不准。m是分钟单位，s是秒的单位，h是小时的单位，不写单位的话默认是毫秒

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hbgj?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: json@1109
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        allow: 127.0.0.1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  mvc:
    favicon:
      enabled: false

    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
    password: passredis@1109
    database: 1
  mail:
    default-encoding: UTF-8
    host: smtp.exmail.qq.com
    username: noreply@ysnewtop.com
    password: pkqS5iotjnFyLGrf
    protocol: smtp
    test-connection: false
#    properties:
#      mail.smtp.auth: true
mybatis:
  type-aliases-package: com.yusheng.hbgj.entity;com.hbgj.modules.*.entity
  mapper-locations: classpath:/mybatis-mappers/*/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
files:
  path: ${file-path:D:/hbgjfiles}

constants:
  hlgjId: 2
  adminId: 1
  companyRoleId: 2
  visitorRoleId: 3

logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: ../hbgjlogs/admin-server.log
  maxsize: 30MB
token:
  expire:
    day: 30
    webExpireDay: 7